# Generated by Django 4.1.3 on 2022-11-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=45)),
                ('currency_code', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRateLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField()),
                ('exchange_rate_date', models.DateField()),
                ('exchange_rate_conversion_value', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.currencyrepository')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=45)),
                ('country_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_scenario_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(max_length=45)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.industry')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueScenarioHasProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_year', models.DateField()),
                ('revenue_value', models.FloatField()),
                ('revenue_unit_numerator', models.CharField(max_length=45)),
                ('revenue_unit_denominator', models.CharField(max_length=45)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.product')),
                ('revenue_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.revenuescenario')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=45)),
                ('project_description', models.CharField(max_length=200)),
                ('project_code', models.CharField(max_length=10)),
                ('project_cost_code', models.CharField(max_length=20)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('project_location', models.CharField(max_length=45)),
                ('project_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.fiscalcountry')),
                ('project_exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.exchangeratelibrary')),
                ('project_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.segment')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.producttype'),
        ),
        migrations.AddField(
            model_name='fiscalcountry',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.region'),
        ),
        migrations.CreateModel(
            name='Exchange_rate_has_current_repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.currencyrepository')),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.exchangeratelibrary')),
            ],
        ),
    ]
