# Generated by Django 4.1.3 on 2022-11-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyName', models.CharField(max_length=45, unique=True)),
                ('CurrencyCode', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRateLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExchangeRateLibraryName', models.CharField(max_length=45)),
                ('CurrencyName', models.CharField(max_length=45)),
                ('Year', models.DateField()),
                ('ExchangeRateConversionValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FiscalCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiscalCountryName', models.CharField(max_length=45, unique=True)),
                ('FiscalCountryCode', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndustryName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductTypeName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionName', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RevenueScenarioName', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SegmentName', models.CharField(max_length=45)),
                ('Industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.industry')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueScenarioHasProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RevenueYear', models.DateField()),
                ('RevenueValue', models.FloatField()),
                ('RevenueUnitNumerator', models.CharField(max_length=45)),
                ('RevenueUnitDenominator', models.CharField(max_length=45)),
                ('RevenueScenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.revenuescenario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.product')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=45, unique=True)),
                ('ProjectDesc', models.CharField(max_length=200)),
                ('ProjectCode', models.CharField(max_length=10, unique=True)),
                ('ProjectCostCode', models.CharField(max_length=20, unique=True)),
                ('ProjectStartDate', models.DateField()),
                ('ProjectEndDate', models.DateField()),
                ('ProjectLocation', models.CharField(max_length=45)),
                ('ExchangeRateLibrary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.exchangeratelibrary')),
                ('ProjectCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.fiscalcountry')),
                ('ProjectSegment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.segment')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ProductType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.producttype'),
        ),
        migrations.AddField(
            model_name='fiscalcountry',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.region'),
        ),
        migrations.CreateModel(
            name='ExchangeRateLibrary_has_CurrentRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyRepository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.currencyrepository')),
                ('ExchangeRateLibrary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.exchangeratelibrary')),
            ],
        ),
    ]
