# Generated by Django 4.1.3 on 2022-11-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_alter_exchangeratelibrary_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalcountry',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FiscalCountry', to='revenue.region'),
        ),
    ]
